version: '3.9'
services:
  
  app:
    build:
      context: .  
    ports:
      - "8000:8000"  
    command: >
      sh -c "sleep 7 && python manage.py makemigrations && 
      python manage.py migrate &&
      python manage.py makesuperuser&&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=root
      - DB_PASS=secret
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      - database
      - cache

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

  database:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret


volumes:
  app:
  cache:
    driver: local
